services:
  database:
    image: postgres:17.2-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yapperz
    volumes:
      - ./postgres:/var/lib/postgresql/data
